# Generated by Django 3.1.14 on 2022-12-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Post',
        ),
    ]
